services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      USERNAME: "<USUARIO>"
      PASSWORD: "<SENHA>"
      LANGUAGE: "English"
      REGION: "pt-BR"
      KEYBOARD: "en-US"
    volumes:
      # Volume do Windows
      - /<PATH>/Win:/storage
      # Volume para pastas compartilhadas
      - /<PATH>/Data:/data
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    restart: always
    stop_grace_period: 2m
